# Site
repository: usama13o/resume-theme
favicon: images/favicon.ico

# Personal info
name: Usama Zidan 
title: Computer Science Graduate 
email: osama.zadan@gmail.com
website: usama13o.github.io

# Social links

github_username:  usama13o
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: usama_zidan
linkedin_username: usamazidan 
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: im.jpg
about_content: | # this will include new lines to allow paragraphs
I'm Usama, a dedicated PhD student at Birmingham City University, holding a BSc in Computer Science with AI from the University of Nottingham. With a diverse range of experiences, I've cultivated strong teamwork and leadership skills while delving into exciting projects.

Proficient in a variety of programming languages, including <mark>Python</mark>, <mark>Java/Kotlin</mark>, <mark>Dart</mark>, and <mark>C/C#</mark>, I bring a versatile skill set to the table.

My journey so far has exposed me to diverse environments and multifaceted tasks. The knowledge I've acquired, whether through collaborative projects or tackling complex challenges, sets me apart. My unique background and expertise in the field contribute to my distinctive problem-solving and teamwork capabilities.

I invite you to explore my website to learn more about me and my exceptional journey. Let's connect and discover how I can be a valuable asset to your team.

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Hiking
   - Gaming
   - Photography
  I enjoy hiking and exploring new places, I have been to many places in the UK and I'm looking forward to exploring more places in the future.

  I'm also interested in photography and videography as I like to be creative, I'm mainly enjoy landscape and abstract photography. 
  I like to showcase my work on instagram if you would like to take a look - [Usama Zidan](https://www.instagram.com/usama_zidan/).
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
