# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Usama Zidan 
title: Computer Science Graduate 
email: osama.zadan@gmail.com
website: usama13o.github.io

# Social links

github_username:  usama13o
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: usama_zidan
linkedin_username: usamazidan 
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: im.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Usama and I'm a graduate of the university of Nottingham UK. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark>, <mark>Java/Kotlin</mark> and <mark>Dart</mark>

# Projects Section
# projects_title: Projects
projects_content: |
  Undergraduate Dissertation
  Designed a Deep Learning framework to segment a pathology from a set of Radio-graphs.
  • Devised an architecture to test the performance of Fully Connected Networks in various setups
  • Investigated relevant approaches in the literature
  • Attained the skills required to work solely on a project while keeping up with the deadlines
  Languages and Technologies  Python, FCNs, Numpy, Scikit-learn, Scrum
# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Hiking
   - Gaming
   - Arting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
