# Site
repository: usama13o/resume-theme
favicon: images/favicon.ico

# Personal info
name: Usama Zidan 
title: Computer Science Graduate 
email: osama.zadan@gmail.com
website: usama13o.github.io

# Social links

github_username:  usama13o
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: usama_zidan
linkedin_username: usamazidan 
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: im.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Usama and I'm a graduate of the university of Nottingham UK. I have worked at a number of projects gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark>, <mark>Java/Kotlin</mark>, <mark>Dart</mark>, <mark>C/C#</mark>, and Full stack Web Devlopment

  My experiences that I had so far gives me an edge to others. I have been exposed to different environments and dealt with different various tasks. The knowledge that I gained, whether in dealing with people or executing tasks, makes me different, my background makes me different, and my expertise in the field makes me different. All of this allows me to provide a package of team working and problem solving that I believe is unique in its own. 


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Hiking
   - Gaming
   - Arting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  I'm also interested in photography and videography as I like to be creative, this is mainly through sport but
  I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
  you would like to take a look -
  [Usama Zidan](https://www.instagram.com/usama_zidan/).
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
